language: python
python:
    - "3.6"
install:
    - pip install matplotlib pylint pyqt5
    - pip install --upgrade https://github.com/revoltek/losoto/archive/master.zip
script:
    - pylint h5plot.py --extension-pkg-whitelist=PyQt5 --errors-only
