""" The spiritual successor to ParmDBplot for quickly reviewing gain solutions generated by NDPPP.
"""
import logging
import signal
import sys

from PyQt5.QtWidgets import QApplication, QComboBox, QDialog, QFormLayout, QGridLayout, QLabel, \
    QListWidget, QPushButton

import losoto.h5parm as lh5
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
plt.ion()

signal.signal(signal.SIGINT, signal.SIG_DFL)

class H5PlotGUI(QDialog):
    """The main GUI for H5Plot.

    From here the SolSets, SolTabs and antennas to plot are selected.
    """
    def __init__(self, h5file, logging_instance, parent=None):
        super(H5PlotGUI, self).__init__(parent)
        self.logger = logging_instance
        self.figures = []

        self.h5parm = lh5.h5parm(h5file)
        self.solset_labels = self.h5parm.getSolsetNames()
        self.solset = self.h5parm.getSolset('sol000')

        self.soltab_labels = self.solset.getSoltabNames()
        self.soltab = self.solset.getSoltab(self.soltab_labels[0])

        self.stations = self.soltab.getValues()[1]['ant']

        self.move(300, 300)
        self.setWindowTitle('H5Plot')

        self.solset_label = QLabel('SolSet: ')
        self.solset_picker = QComboBox()
        for l in self.solset_labels:
            self.solset_picker.addItem(l)
        self.solset_picker.activated.connect(self._solset_picker_event)

        self.soltab_label_y = QLabel('Plot ')
        self.soltab_label_x = QLabel(' vs ')
        self.soltab_picker = QComboBox()
        for l in self.soltab_labels:
            self.soltab_picker.addItem(l)
        self.soltab_picker.activated.connect(self._soltab_picker_event)
        self.axis_picker = QComboBox()
        self.axis_picker.addItems(['time', 'freq'])
        self.axis_picker.activated.connect(self._axis_picker_event)
        self.axis = 'time'

        self.plot_button = QPushButton('Plot')
        self.plot_button.clicked.connect(self._plot_button_event)

        self.station_picker = QListWidget()
        self.station_picker.addItems(self.stations)
        self.station_picker.setCurrentRow(0)


        plot_layout = QGridLayout()
        plot_layout.addWidget(self.soltab_label_y, 0, 0)
        plot_layout.addWidget(self.soltab_picker, 0, 1)
        plot_layout.addWidget(self.soltab_label_x, 0, 2)
        plot_layout.addWidget(self.axis_picker, 0, 3)

        layout = QFormLayout(self)
        layout.addRow(self.solset_label, self.solset_picker)
        layout.addRow(plot_layout)
        layout.addRow(self.plot_button)
        layout.addRow(self.station_picker)

    def _axis_picker_event(self):
        """Callback function for when the x-axis is changed.

        Sets the `axis` attribute to the selected axis
        """
        self.logger.debug('Axis changed to: ' + self.axis_picker.currentText())
        self.axis = self.axis_picker.currentText()

    def closeEvent(self, event):
        self.logger.info('Closing all open figures before exiting.')
        plt.close('all' )
        event.accept()

    def _solset_picker_event(self):
        """Callback function for when the SolSet is changed.

        Sets the `solset` attribute.
        """
        self.logger.debug('Solset changed to: ' + self.solset_picker.currentText())
        self.solset = self.h5parm.getSolset(self.solset_picker.currentText())

    def _soltab_picker_event(self):
        """Callback function for when the SolTab is changed.

        Sets the `soltab` attribute.
        """
        self.logger.debug('Soltab changed to: ' + self.soltab_picker.currentText())
        self.soltab = self.solset.getSoltab(self.soltab_picker.currentText())

    def _plot_button_event(self):
        """Callback function for when the plot button is pressed.

        Calls the `plot` function subsecquently.
        """
        self.logger.debug('Plotting button pressed.')
        self.plot(labels=(self.axis, self.soltab.name))

    def plot(self, labels=('x-axis', 'y-axis'), limits=([None, None], [None, None])):
        self.logger.info('Plotting ' + self.soltab.name + ' vs ' + self.axis + \
                         ' for ' + self.solset.name)
        fig = plt.figure()
        ax = fig.add_subplot(111)
        antenna = self.station_picker.currentRow()
        ax.set_title(self.stations[antenna])
        # Values have shape (timestamps, frequencies, antennas, polarizations).
        # For LoSoTo < 2.0 values have shape (polarizations, directions, antennas, frequencies, timestamps).
        values = self.soltab.getValues()[0]
        x_axis = self.soltab.getValues()[1][self.axis]

        # Common rotation angle has no polarization axis, so needs to be treated a bit differently.
        if ('rotation' in self.soltab.name) and ('dir' in self.soltab.getValues()[1].keys()):
            # LoSoTo 1.0 order
            if self.axis == 'time':
                y_axis = values[0, antenna, 0, :]
            elif self.axis == 'freq':
                y_axis = values[0, antenna, :, 0]
            ax.plot(x_axis, y_axis, 'h')
        else:
            if ('dir' in self.soltab.getValues()[1].keys()) and (list(self.soltab.getValues()[1].keys())[-1] == 'time'):
                # LoSoTo < 2.0 order; pick the 0th direction.
                if self.axis == 'time':
                    y_axis = [values[pol, 0, antenna, 0, :] for pol in range(values.shape[0])]
                elif self.axis == 'freq':
                    y_axis = [values[pol, 0, antenna, :, 0] for pol in range(values.shape[0])]
            elif ('dir' in self.soltab.getValues()[1].keys()) and (list(self.soltab.getValues()[1].keys())[0] == 'time'):
                # LoSoTo 2.0 order.
                pass
            elif ('dir' not in self.soltab.getValues()[1].keys()) and (list(self.soltab.getValues()[1].keys())[-1] == 'time'):
                # LoSoTo < 2.0 order.
                pass
            elif ('dir' not in self.soltab.getValues()[1].keys()) and (list(self.soltab.getValues()[1].keys())[0] == 'time'):
                # LoSoTo 2.0 order.
                if self.axis == 'time':
                    y_axis = [values[:, 0, antenna, pol] for pol in range(values.shape[-1])]
                elif self.axis == 'freq':
                    y_axis = [values[0, :, antenna, pol] for pol in range(values.shape[-1])]

            for i, y in enumerate(y_axis):
                ax.plot(x_axis, y, 'h', label=self.soltab.getValues()[1]['pol'][i])
            ax.legend()
        ax.set(xlabel=self.axis, ylabel=labels[1], xlim=limits[0], ylim=limits[1])
        self.figures.append(fig)
        fig.show()


if __name__ == '__main__':
    FILENAME = sys.argv[1]
    H5FILE = lh5.h5parm(FILENAME, readonly=True)
    # Set up for logging output.
    LOGGER = logging.getLogger('H5plot_logger')
    LOGGER.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    LOGFILEH = logging.FileHandler('h5plot.log')
    LOGFILEH.setLevel(logging.DEBUG)
    LOGFILEH.setFormatter(formatter)
    LOGGER.addHandler(LOGFILEH)

    LOGGER.info('Successfully opened %s', FILENAME)

    SOLSETS = H5FILE.getSolsetNames()
    print('Found solset(s) '+ ', '.join(SOLSETS))
    for solset in SOLSETS:
        print('SolTabs in ' + solset + ':')
        ss = H5FILE.getSolset(solset)
        soltabs = ss.getSoltabNames()
        print('\t', end='')
        print(', '.join(soltabs))

    # Initialize the GUI.
    APP = QApplication(sys.argv)
    GUI = H5PlotGUI(FILENAME, LOGGER)
    GUI.show()
    APP.exec_()

    H5FILE.close()
    LOGGER.info('%s successfully closed.', FILENAME)
