import setuptools

with open('README.md', 'r') as f:
    long_desc = f.read()

setuptools.setup(
    name='lofar-h5plot',
    version='2.9.5',
    scripts=['h5plot'],
    author='Frits Sweijen',
    author_email='frits.sweijen@gmail.com',
    description='The spiritual successor to ParmDBplot for quickly reviewing gain solutions generated by NDPPP.',
    long_description=long_desc,
    long_description_content_type='text/markdown',
    url='https://github.com/jomdh/lofar-h5plot',
    packages=setuptools.find_packages(),
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.10',
    install_requires=[
        'qtpy',
        'PySide6; platform_machine == "aarch64" and sys_platform == "linux"',
        'PyQt5; platform_machine != "aarch64" or sys_platform != "linux"',
        'losoto',
        'matplotlib',
        'numpy',
    ],
)
